/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 cubic.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cubic(props) {
  const { nodes, materials } = useGLTF('/models/cubic/cubic.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['154377_23_01_08_01_11_00_1'].geometry} material={materials['154377_23_01_08_01_11_00_1']} 
      position={[3.31, 4.67, 2.05]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cubic.gltf')
